### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by wangbq18** [bowang-lab/joint-ner-and-re#3]
Hi,

Yes we are just working on cleaning it up in the coming weeks. For now, you can have a look at the code here: https://github.com/BaderLab/saber/tree/development

_Originally posted by @JohnGiorgi in https://github.com/bowang-lab/joint-ner-and-re/issues/2#issuecomment-575609130_

**Comment by wangbq18** [comment]
got it! thanks!

**Comment by JohnGiorgi** [comment]
This looks like a copy-paste of my response? Closing for now. Please re-open if you have another question.
